### ISSUE TITLE
Cannot run code

### ISSUE THREAD

**Issue by mzhubail** [bahrain-uob/gen-ai-moe-challenge#73]
I'm on main trying to run local development `npm run dev` and I get the following error

```
Error: Invalid character in header content ["authorization"]

Trace: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["authorization"]
    at ClientRequest.setHeader (node:_http_outgoing:706:3)
    at new ClientRequest (node:_http_client:289:14)
    at request (node:https:378:10)
    at /home/mzh/Repositories/gen-ai-moe-challenge/node_modules/@smithy/node-http-handler/dist-cjs/index.js:294:19
    at new Promise (<anonymous>)
    at _NodeHttpHandler.handle (/home/mzh/Repositories/gen-ai-moe-challenge/node_modules/@smithy/node-http-handler/dist-cjs/index.js:245:12)
    at async /home/mzh/Repositories/gen-ai-moe-challenge/node_modules/@smithy/middleware-serde/dist-cjs/index.js:33:24
    at async /home/mzh/Repositories/gen-ai-moe-challenge/node_modules/@smithy/core/dist-cjs/index.js:165:18
    at async StandardRetryStrategy.retry (/home/mzh/Repositories/gen-ai-moe-challenge/node_modules/@aws-sdk/middleware-retry/node_modules/@smithy/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /home/mzh/Repositories/gen-ai-moe-challenge/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22
    at async file:///home/mzh/Repositories/gen-ai-moe-challenge/node_modules/sst/credentials.js:43:22
    at async Promise.all (index 0)
    at async Object.handler (file:///home/mzh/Repositories/gen-ai-moe-challenge/node_modules/sst/cli/commands/deploy.js:28:41)
    at process.<anonymous> (file:///home/mzh/Repositories/gen-ai-moe-challenge/node_modules/sst/cli/sst.js:58:21)
    at process.emit (node:events:531:35)
    at process.emit (node:domain:488:12)
    at process._fatalException (node:internal/process/execution:178:25)
    at processPromiseRejections (node:internal/process/promises:289:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

This error is also shown with previous code that we know to work well (ba7e9cd7 for example).  The error is also shown when trying to run `npx sst deploy` too.

Help would be appreciated @cerashdan @maramesk

**Comment by mzhubail** [comment]
My guess is that AWS have updated some stuff on their end and we have to bump some libraries to a newer version.
